### ISSUE TITLE
Error: undefined

### ISSUE THREAD

**Issue by thomastsaidotcom** [propertybase/propertybase-website-demo#1]
On your live version it works great. However, when I download the code from your github. I'm getting plenty of errors.

My logs are stating that in search.php
!isset($response->listings[0]) is triggering, which means that looking for a listing in response is returning null

This only occurs when using scripts.js or the index.html page. When accessing the php file directly and echoing responses from there, everything is fine.

**Comment by PeterSiegl** [comment]
I reproduced the issue and pushed a fix. 

The error occurred on the initial page load when no URL parameters were present. In this case the backend tried to query the field `Featured_on_Website__c` which is not part of the default configuration.

Thanks for letting me know!
